apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: libvirt
spec:
  label: libvirt
  playbook: osp.edpm.libvirt
  tlsCert:
    contents:
      - dnsnames
      - ips
    networks:
      - CtlPlane
    issuer: osp-rootca-issuer-internal
  caCerts: combined-ca-bundle
